name: Kali-RDP

on:
  workflow_dispatch:

jobs:
  kali-rdp:
    runs-on: ubuntu-latest
    container:
      image: kalilinux/kali-rolling
    timeout-minutes: 1440

    steps:
      - name: Update & Install Desktop + RDP
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y \
            xrdp xfce4 xfce4-goodies dbus-x11 x11-xserver-utils \
            curl wget sudo

          # إنشاء مستخدم للدخول
          useradd -m -s /bin/bash rdpuser
          echo "rdpuser:Password123!" | chpasswd
          adduser rdpuser sudo

          # إعداد سطح المكتب الافتراضي
          echo "xfce4-session" > /home/rdpuser/.xsession
          chown rdpuser:rdpuser /home/rdpuser/.xsession

          # تشغيل خدمة RDP
          service xrdp restart

      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          # تشغيل tailscaled بالخلفية بدون systemd
          nohup tailscaled > /dev/null 2>&1 &

      - name: Connect to Tailscale
        run: |
          tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=kali-rdp-${{ github.run_id }}
          TS_IP=$(tailscale ip -4 | head -n 1)
          echo "TAILSCALE_IP=$TS_IP" >> $GITHUB_ENV

      - name: Show RDP Credentials
        run: |
          echo "=============================="
          echo "✅ Kali RDP is ready!"
          echo "Connect with:"
          echo "Address: $TAILSCALE_IP:3389"
          echo "Username: rdpuser"
          echo "Password: Password123!"
          echo "=============================="
          
      - name: Keep alive
        run: |
          while true; do
            echo "[$(date)] RDP running..."
            sleep 300
          done
