name: Linux

on:
  workflow_dispatch:

jobs:
  secure-rdp:
    runs-on: ubuntu-latest
    timeout-minutes: 1440

    steps:
      - name: Configure Core RDP Settings
        run: |
          sudo apt-get update
          sudo apt-get install -y xrdp xfce4 xfce4-goodies
          
          # Enable XRDP service
          sudo systemctl enable xrdp
          sudo systemctl start xrdp
          
          # Allow RDP traffic on port 3389
          sudo ufw allow 3389/tcp || true

      - name: Create RDP User with Fixed Password
        run: |
          USER="rdpuser"
          PASS="l1shere!"
          
          if id "$USER" &>/dev/null; then
              echo "User $USER already exists, updating password..."
              echo "$USER:$PASS" | sudo chpasswd
          else
              sudo useradd -m -s /bin/bash "$USER"
              echo "$USER:$PASS" | sudo chpasswd
              sudo usermod -aG sudo "$USER"
          fi
          
          echo "RDP_USER=$USER" >> $GITHUB_ENV
          echo "RDP_PASS=$PASS" >> $GITHUB_ENV

      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh

      - name: Establish Tailscale Connection
        run: |
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=gh-runner-${GITHUB_RUN_ID}
          
          # Get Tailscale IP
          tsIP=$(tailscale ip -4 | head -n 1)
          if [ -z "$tsIP" ]; then
              echo "Tailscale IP not assigned. Exiting."
              exit 1
          fi
          echo "TAILSCALE_IP=$tsIP" >> $GITHUB_ENV

      - name: Verify RDP Accessibility
        run: |
          echo "Tailscale IP: $TAILSCALE_IP"
          nc -zv $TAILSCALE_IP 3389 || (echo "TCP connection to RDP port 3389 failed" && exit 1)
          echo "TCP connectivity successful!"

      - name: Maintain Connection
        run: |
          echo ""
          echo "=== RDP ACCESS ==="
          echo "Address: $TAILSCALE_IP"
          echo "Username: $RDP_USER"
          echo "Password: $RDP_PASS"
          echo "=================="
          echo ""
          
          while true; do
              echo "[$(date)] RDP Active - Use Ctrl+C in workflow to terminate"
              sleep 300
          done
